#!/usr/bin/env python3
"""
Comprehensive explanation and demonstration of RAG scoring system
"""
import os
os.environ['KMP_DUPLICATE_LIB_OK'] = 'TRUE'

from txtai import Embeddings
from rag_backend import rag_query_enhanced

def explain_scoring_system():
    print("=" * 80)
    print("🔍 RAG SCORING SYSTEM EXPLAINED")
    print("=" * 80)
    
    print("""
The scoring in your RAG system happens in multiple stages:

1️⃣  EMBEDDING SIMILARITY SCORES (0.0 to 1.0)
   • Generated by txtai using sentence-transformers model
   • Cosine similarity between query and chunk embeddings
   • Higher = more similar (0.6+ is good, 0.5+ is decent)
   • Range: 0.0 (completely different) to 1.0 (identical)

2️⃣  CROSS-ENCODER RERANKING SCORES (can be negative)
   • Uses a different model to rerank the initial results
   • More sophisticated than simple embedding similarity
   • Can be negative (lower relevance) or positive (higher relevance)
   • Final scores used for chunk ordering

3️⃣  HYBRID SEARCH SCORES (CURRENTLY ENABLED)
   • Combines embedding similarity + BM25 keyword matching
   • Uses BM25Okapi algorithm for sparse retrieval
   • Weighted average: 70% semantic + 30% keyword (HYBRID_ALPHA=0.7)
   • BM25 parameters: k1=1.2, b=0.75
   
Let's see this in action:
""")
    
    try:
        # Load embeddings for direct testing
        print("Loading embeddings for direct testing...")
        embeddings = Embeddings({'path': 'sentence-transformers/all-MiniLM-L6-v2', 'content': True})
        embeddings.load('business-docs-index')
        
        # Test query
        query = "what is the rent for second year"
        print(f"\n🔍 QUERY: '{query}'")
        
        print("\n" + "-" * 60)
        print("1️⃣  INITIAL EMBEDDING SIMILARITY SCORES")
        print("-" * 60)
        
        initial_results = embeddings.search(query, 5)
        for i, result in enumerate(initial_results):
            score = result['score']
            chunk_id = result['id'].split('\\')[-1]  # Just filename
            text_preview = result.get('text', '')[:100]
            
            # Determine quality level
            if score >= 0.6:
                quality = "🟢 EXCELLENT"
            elif score >= 0.5:
                quality = "🟡 GOOD"
            elif score >= 0.4:
                quality = "🟠 FAIR"
            else:
                quality = "🔴 POOR"
                
            print(f"{i+1}. Score: {score:.3f} {quality}")
            print(f"   ID: {chunk_id}")
            print(f"   Text: {text_preview}...")
            print()
        
        print("\n" + "-" * 60)
        print("2️⃣  FULL RAG PIPELINE WITH RERANKING")
        print("-" * 60)
        
        # Run full RAG pipeline
        rag_result = rag_query_enhanced(
            question=query,
            embeddings=embeddings,
            topn=5,
            enable_reranking=True
        )
        
        chunks = rag_result.get('chunks', [])
        print(f"Final chunks after reranking: {len(chunks)}")
        
        for i, chunk in enumerate(chunks):
            # Get different score types
            initial_score = chunk.get('retrieval_score', 'N/A')
            rerank_score = chunk.get('final_rerank_score', 'N/A')
            combined_score = chunk.get('combined_score', 'N/A')
            
            text_preview = chunk.get('text', chunk.get('chunk_text', ''))[:100]
            chunk_id = chunk.get('chunk_id', 'Unknown').split('\\')[-1]
            
            print(f"{i+1}. CHUNK: {chunk_id}")
            print(f"   Initial Score:  {initial_score}")
            print(f"   Rerank Score:   {rerank_score}")
            print(f"   Combined Score: {combined_score}")
            print(f"   Text: {text_preview}...")
            print()
            
        print("\n" + "=" * 60)
        print("📊 SCORING INTERPRETATION GUIDE")
        print("=" * 60)
        print("""
EMBEDDING SIMILARITY SCORES:
• 0.7+ = Highly relevant (rare, excellent match)
• 0.6+ = Very relevant (good semantic match)  
• 0.5+ = Moderately relevant (decent match)
• 0.4+ = Somewhat relevant (may contain useful info)
• <0.4 = Likely not relevant

CROSS-ENCODER RERANKING SCORES:
• Positive scores = Higher relevance than average
• Scores near 0 = Average relevance
• Negative scores = Lower relevance than average
• Very negative (-5+) = Poor relevance

WHY SCORES MATTER:
• Initial scores determine which chunks are retrieved
• Reranking scores determine final order sent to LLM
• Your system now retrieves top 4-6 chunks instead of 3
• This captures more potentially relevant content
""")
        
    except Exception as e:
        print(f"ERROR: {e}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    explain_scoring_system()
